import type { User, Complaint } from "./types"

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Arjun Mehta",
    username: "arjun_m",
    email: "arjun@email.com",
    phone: "9876543210",
    address: "12 MG Road, Sector 5",
    role: "citizen",
    region: "Sector 5",
  },
  {
    id: "u2",
    name: "Priya Sharma",
    username: "priya_s",
    email: "priya@email.com",
    address: "45 Gandhi Nagar, Sector 12",
    role: "citizen",
    region: "Sector 12",
  },
  {
    id: "u3",
    name: "Municipal Officer - Sector 5",
    username: "muni_sec5",
    email: "muni5@gov.in",
    address: "Municipal Office, Sector 5",
    role: "authority",
    region: "Sector 5",
  },
  {
    id: "u4",
    name: "Rahul Verma",
    username: "rahul_v",
    email: "rahul@email.com",
    address: "78 Nehru Street, Sector 5",
    role: "citizen",
    region: "Sector 5",
  },
]

export const mockComplaints: Complaint[] = [
  {
    id: "c1",
    title: "Massive pothole on MG Road causing accidents",
    description:
      "There is a large pothole near the intersection of MG Road and Park Street that has been causing accidents for the past two weeks. Multiple vehicles have been damaged. The pothole is approximately 3 feet wide and 1 foot deep. Immediate repair is needed before someone gets seriously injured.",
    category: "road",
    status: "unsolved",
    location: "MG Road near Park Street intersection, Sector 5",
    region: "Sector 5",
    latitude: 28.6139,
    longitude: 77.209,
    images: [],
    userId: "u1",
    userName: "Arjun Mehta",
    likes: 47,
    likedByCurrentUser: false,
    facingSameIssue: 23,
    comments: [
      {
        id: "cm1",
        userId: "u1",
        userName: "Arjun Mehta",
        userRole: "citizen",
        content:
          "This pothole has been here for over 2 weeks now. Please take action immediately.",
        createdAt: "2026-02-10T10:30:00Z",
      },
      {
        id: "cm2",
        userId: "u3",
        userName: "Municipal Officer - Sector 5",
        userRole: "authority",
        content:
          "We have noted this complaint. Our team will inspect the area within 48 hours.",
        createdAt: "2026-02-11T09:15:00Z",
      },
    ],
    createdAt: "2026-02-05T08:00:00Z",
    updatedAt: "2026-02-11T09:15:00Z",
  },
  {
    id: "c2",
    title: "Garbage piling up at Gandhi Nagar junction",
    description:
      "Garbage has been accumulating at the Gandhi Nagar junction for the past week. The collection truck has not come since last Monday. The smell is unbearable and it is attracting stray animals. This is a health hazard for the entire neighborhood.",
    category: "garbage",
    status: "in_progress",
    location: "Gandhi Nagar Junction, Sector 12",
    region: "Sector 12",
    latitude: 28.6129,
    longitude: 77.2295,
    images: [],
    userId: "u2",
    userName: "Priya Sharma",
    likes: 92,
    likedByCurrentUser: true,
    facingSameIssue: 56,
    comments: [
      {
        id: "cm3",
        userId: "u2",
        userName: "Priya Sharma",
        userRole: "citizen",
        content:
          "It has been a week now. The garbage is spreading to the nearby streets too.",
        createdAt: "2026-02-12T14:00:00Z",
      },
    ],
    createdAt: "2026-02-08T12:00:00Z",
    updatedAt: "2026-02-14T16:00:00Z",
  },
  {
    id: "c3",
    title: "Blocked drainage causing waterlogging on Nehru Street",
    description:
      "The main drainage on Nehru Street has been blocked for 3 days. Every time it rains, the entire street gets waterlogged. Water is entering houses in the low-lying area. Please send a team to clear the drainage immediately.",
    category: "drainage",
    status: "on_the_way",
    location: "Nehru Street, Near Block C, Sector 5",
    region: "Sector 5",
    latitude: 28.6145,
    longitude: 77.2103,
    images: [],
    userId: "u4",
    userName: "Rahul Verma",
    likes: 35,
    likedByCurrentUser: false,
    facingSameIssue: 18,
    comments: [],
    createdAt: "2026-02-13T07:30:00Z",
    updatedAt: "2026-02-15T11:00:00Z",
  },
  {
    id: "c4",
    title: "Broken water pipeline leaking for days",
    description:
      "A water pipeline has burst near the community park. Clean drinking water is being wasted continuously. The area around the leak has become slippery and dangerous for pedestrians. This has been going on for 5 days without any action.",
    category: "water_supply",
    status: "read",
    location: "Community Park, Block A, Sector 5",
    region: "Sector 5",
    latitude: 28.615,
    longitude: 77.2088,
    images: [],
    userId: "u1",
    userName: "Arjun Mehta",
    likes: 28,
    likedByCurrentUser: true,
    facingSameIssue: 14,
    comments: [],
    createdAt: "2026-02-14T09:00:00Z",
    updatedAt: "2026-02-15T08:00:00Z",
  },
  {
    id: "c5",
    title: "Street lights not working on entire stretch of Road No. 7",
    description:
      "All the street lights on Road No. 7 from the main chowk to the hospital have been non-functional for a week. This makes the road extremely dangerous at night, especially for women and children. Multiple robberies have been reported in the area.",
    category: "electricity",
    status: "solved",
    location: "Road No. 7, Sector 5",
    region: "Sector 5",
    latitude: 28.6155,
    longitude: 77.2115,
    images: [],
    proofImage: "/placeholder-proof.jpg",
    userId: "u4",
    userName: "Rahul Verma",
    likes: 64,
    likedByCurrentUser: false,
    facingSameIssue: 41,
    comments: [
      {
        id: "cm4",
        userId: "u3",
        userName: "Municipal Officer - Sector 5",
        userRole: "authority",
        content:
          "All street lights have been repaired. Uploading proof image for verification.",
        createdAt: "2026-02-16T17:00:00Z",
      },
    ],
    createdAt: "2026-02-01T18:00:00Z",
    updatedAt: "2026-02-16T17:00:00Z",
    resolvedAt: "2026-02-16T17:00:00Z",
  },
  {
    id: "c6",
    title: "Open manhole on school road - extremely dangerous",
    description:
      "There is an open manhole right in front of City Public School on Road No. 3. The cover has been missing for 2 days. Children walk this road every day to school. This is an emergency situation that needs immediate attention.",
    category: "sanitation",
    status: "verified",
    location: "Road No. 3, Near City Public School, Sector 5",
    region: "Sector 5",
    latitude: 28.6148,
    longitude: 77.2098,
    images: [],
    proofImage: "/placeholder-proof.jpg",
    userId: "u1",
    userName: "Arjun Mehta",
    likes: 112,
    likedByCurrentUser: true,
    facingSameIssue: 78,
    comments: [
      {
        id: "cm5",
        userId: "u3",
        userName: "Municipal Officer - Sector 5",
        userRole: "authority",
        content: "Manhole cover has been replaced with a new heavy-duty cover.",
        createdAt: "2026-02-12T14:30:00Z",
      },
      {
        id: "cm6",
        userId: "u1",
        userName: "Arjun Mehta",
        userRole: "citizen",
        content:
          "Verified! The new cover has been properly installed. Thank you for the quick action.",
        createdAt: "2026-02-13T08:00:00Z",
      },
    ],
    createdAt: "2026-01-28T06:00:00Z",
    updatedAt: "2026-02-13T08:00:00Z",
    resolvedAt: "2026-02-12T14:30:00Z",
    verifiedAt: "2026-02-13T08:00:00Z",
  },
  {
    id: "c7",
    title: "Garbage dump near residential area attracting pests",
    description:
      "An unauthorized garbage dump has formed near Block D residential area. It is attracting rats, mosquitoes, and stray dogs. Multiple residents have complained about foul smell. Need immediate cleanup and regular monitoring.",
    category: "garbage",
    status: "unsolved",
    location: "Block D, Near Parking Area, Sector 5",
    region: "Sector 5",
    latitude: 28.6142,
    longitude: 77.2092,
    images: [],
    userId: "u4",
    userName: "Rahul Verma",
    likes: 55,
    likedByCurrentUser: false,
    facingSameIssue: 32,
    comments: [],
    createdAt: "2026-02-16T10:00:00Z",
    updatedAt: "2026-02-16T10:00:00Z",
  },
  {
    id: "c8",
    title: "Road caving in near the new metro construction",
    description:
      "The road near the metro construction site is caving in from the sides. Large cracks have appeared on the surface. This could lead to a major collapse if not attended to immediately. Heavy vehicles are still using this road.",
    category: "road",
    status: "unsolved",
    location: "Metro Site Road, Block B, Sector 12",
    region: "Sector 12",
    latitude: 28.6125,
    longitude: 77.2285,
    images: [],
    userId: "u2",
    userName: "Priya Sharma",
    likes: 73,
    likedByCurrentUser: false,
    facingSameIssue: 45,
    comments: [],
    createdAt: "2026-02-17T08:00:00Z",
    updatedAt: "2026-02-17T08:00:00Z",
  },
]

export const regions = [
  "All Regions",
  "Sector 5",
  "Sector 12",
  "Sector 18",
  "Sector 22",
]

export const categoryLabels: Record<string, string> = {
  road: "Road",
  garbage: "Garbage",
  drainage: "Drainage",
  water_supply: "Water Supply",
  electricity: "Electricity",
  sanitation: "Sanitation",
  other: "Other",
}

export const statusLabels: Record<string, string> = {
  unsolved: "Unsolved",
  read: "Read",
  on_the_way: "On the Way",
  in_progress: "In Progress",
  solved: "Solved",
  verified: "Verified",
}

export const statusColors: Record<string, string> = {
  unsolved: "bg-destructive/10 text-destructive",
  read: "bg-primary/10 text-primary",
  on_the_way: "bg-warning/20 text-warning-foreground",
  in_progress: "bg-chart-4/20 text-foreground",
  solved: "bg-success/15 text-success",
  verified: "bg-success/25 text-success",
}
